import 'package:get/get.dart';

class Transation extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'ar_MA': {
          "Filtrer":"فلتر",
          'EFFACER':'لمحو',
          'Que rechercher vous ?':'عن ماذا تبحث؟',
          "entre ville":"أدخل المدينة",
          "Area ": "النطاق ",
          'Price': "الثمن:",
          'Age': "العمر :",
          'Flooring': 'نوع الأرضية',
          "Bedroms": "غرف النوم",
          "Kitchens": "المطابخ",
          "Bathrooms": "الحمامات",
          'Main Abilites': 'القدرات الرئيسية',
          'Addition Abilites': "قدرات إضافية",
          'Innir Abilites': "القدرات الداخلية",
          "following": "التالي",
          "Reservez ": "ريزيرفز",
          "update": "التحديث",
          "Your ad is not adding": "لم تتم إضافة إعلانك",
          "Your ad is added": "تمت إضافة إعلانك",
          "success": "نجاح",
          "Precedent": "السابق",
          'Phone 1 :': 'الهاتف 1 :',
          'Phone 2 :': 'الهاتف 2 :',
          'Phone 3 :': 'الهاتف 3 :',
          " Entre L \' Phone": "أدخل الهاتف",
          " Entre L \' Description": 'أدخل الوصف',
          'Description :': "الوصف",
          " Entre L \' Titel": "أدخل العنوان",
          "Title": "العنوان",
          'Vender': 'نشر',
          'Property details': 'تفاصيل اوضح',
          'Vente': 'بيع',
          'À location': 'للايجار',
          'Catégorie': 'فئة',
          'Adresse': 'عنوان',
          'Statut': 'الحالة',
          'Region': 'منطقة',
          'Ville': 'مدينة',
          'Quartier': 'حي',
          'select property': 'اختر خاصية',
          'Location': 'تأجير',
          'France': 'الفرنسية',
          'English': 'الانجليزية',
          'Arabic': 'العربية',
          'Suivant': 'التالي',
          'Langues': 'تغيير اللغة',
          'Contactez nous': 'اتصل بنا',
          'Choose Your Language': "اختر لغتك",
          'RECHERCHER (56242)': 'بحث (56242)',
          'Contact': 'دردشة',
          'favoris': 'المفضلة لدي',
          'connecter': 'تسجيل دخول',
          'DEPOSER UNE ANNONCE': 'نشر اعلان',
          "Bienvenue ,": 'مرحبا ،',
          'pour une experience optimisee , ': 'لتجربة محسّنة ،',
          'veuillez vous connecter': 'الرجاء تسجيل الدخول',
          "Neuf": 'جديد',
          "Bon état": 'بحالة جيدة',
          "A besoin de réparation": 'يتطلب الصيانة',
          'Appartements': 'شقق',
          'Chambre': 'غرفة',
          'Maison': 'منزل',
          'Villa': 'فيلا',
          'Riad': 'رياض',
          'Commercial': "محل تجاري",
          'Bureau': 'مكتب',
          'Terre': 'أرض',
          'Fermes': 'مزارع',
          "All": 'الكل',
          "apartment": 'شقق',
          "rooms": 'غرفة',
          "house": 'منزل',
          "villa": 'فيلا',
          "riad": 'رياض',
          'commercialeSpace': 'محل تجاري',
          'office': 'مكتب',
          'land': 'أرض',
          'farm': 'مزارع',
          'Informations': 'معلومات',
          "Se Déconnecter": 'تسجيل الخروج',
          "Tableau De Bord": 'لوحة القيادة',
          "Select State": 'حالة الملكية',
          "Home": 'الرئيسية',
          "This feature will be": "هذه الميزة سوف تكون",
          "available": "متاحة",
          "soon in the application": "  قريبا في التطبيق",
          "Sorry !  ": "نحن اسفون !!",
          "Your Email": "الايميل",
          'Login': 'تسجيل الدخول',
          "Don’t have an Account ": "لا أملك حسابا ",
          "Sign Up": 'انشاء حساب',
          "Are you wante to modifier ?": "هل تريد تعديل هذا الاعلان ؟ ",
          "Cancel": "الغاء",
          "yes": "نعم",
          "this feature is not yet available in this version of the application ":
              "هذه الميزة غير متوفرة بعد في هذا الإصدار من التطبيق",
          "Wooden": "التخشيب",
          'Marble': "الرخام",
          "Tiled": "البلاط",
          "Others": "مواد أخرى",
          "Update": "تعديل",
          "Valider": "مؤكد",
          "Non valider": "غير مؤكد",
          "Post": "الإعلانات",
          "Bord": 'حسابي',
          "Description": 'الوصف',
          "Autre Annonces": 'الإعلانات',
          "Delete": "حذف",
          "Sale": "بيع",
          "Rent": "للايجار",
          "SHOW NUMBER": "إضهار الرقم",
          "SEND MESSAGE": "إرسال رسالة",
          "Baths": "الحمامات",
          "Beds": "سرير",
          "Moins de 1 ans":'أقل من 1 سنة',
          "1 à 5 ans":"'من 1 إلى 5 سنوا'",
          "5 à 10 ans":'من 5 إلى 10 سنوات',
          "10 à 20 ans": 'من 10 إلى 20 سنة',
          "20 à 30 ans":'من 20 إلى 30 سنة',
          "30 à 50 ans":'من 30 إلى 50 سنة',
          "50 à 70 ans": 'من 50 إلى 70 سنة',
          "70 à 100 ans":"من 70 إلى 100 سنة",
          "Plus de 100 ans":'أكثر من 100 عام',
         'Se connecter': 'تسجيل الدخول',
          'Compte':'حساب',
          "Entrez le nom de la ville ?":"أدخل اسم المدينة",
          "Demande":"طلب",
          "Type d\'annonce":"نوع الاعلان",
        },
        'fr_FR': {
          "Filtrer":"Filtrer",
          'EFFACER':'EFFACER',
          'Que rechercher vous ?':"Que rechercher vous ?",
          "entre ville":"entre ville",
          "Entrez le nom de la ville ?":"Entrez le nom de la ville ?",
          "Type d\'annonce":"Type d\'annonce",
          'Compte':'Compte',
          "SHOW NUMBER": "AFFICHER LE NUMÉRO",
          "SEND MESSAGE": "ENVOYER UN MESSAGE",
          "Area ": "Zone ",
          'Price': "Prix:",
          'Age': "Âge :",
          'Flooring': 'Revêtement De Sol',
          "Bedroms": "Les Chambres",
          "Kitchens": "Cuisines",
          "Bathrooms": "Salles De Bains",
          'Main Abilites': 'Capacités Principales',
          'Innir Abilites': "Capacités Intérieures",
          'Addition Abilites': 'Capacités supplémentaires',
          "following": "Suivant",
          "Reservez ": "Réservez",
          "update": "modifier",
          "Your ad is not adding": "Votre annonce n'est pas ajoutée",
          "Your ad is added": "Votre annonce est ajouté",
          "success": "succès",
          "Precedent": "Précédent",
          'Phone 1 :': 'Téléphoner 1: ',
          'Phone 2 :': 'Téléphoner 2: ',
          'Phone 3 :': 'Téléphoner 3:',
          " Entre L \' Phone": " Entre L \' Téléphoner",
          " Entre L \' Description": " Entre L \' Description",
          'Description :': "Description :",
          " Entre L \' Titel": "Entre L\'Titre",
          "Title": "Titre",
          "Error": "Error",
          "Select State": "Select State",
          "Se Déconnecter": 'Se Déconnecter',
          "Tableau De Bord": 'Tableau De Bord',
          'Informations': 'Informations',
          'All': 'Tout',
          'apartment': 'Appartements',
          'rooms': 'Chambre',
          'house': 'Maison',
          'villa': 'Villa',
          'riad': 'Riad',
          'commercialeSpace': 'Commercial',
          'office': 'Bureau',
          'land': 'Terre',
          'farm': 'Fermes',
          'Appartements': 'Appartements',
          'Chambre': 'Chambre',
          'Maison': 'Maison',
          'Villa': 'Villa',
          'Riad': 'Riad',
          'Commercial': 'Commercial',
          'Bureau': 'Bureau',
          'Terre': 'Terre',
          'Fermes': 'Fermes',
          "Neuf": "Neuf",
          "Bon état": "Bon état",
          "A besoin de réparation": "A besoin de réparation",
          'Suivant': 'Suivant',
          'Property details': 'Property details',
          'Vente': 'Vente',
          'À location': 'À location',
          'Catégorie': 'Catégorie',
          'Adresse': 'Adresse',
          'Statut': 'Statut',
          'Region': 'Region',
          'Ville': 'Ville',
          'Quartier': 'Quartier',
          'select property': 'select property',
          'Location': 'Location',
          'veuillez vous connecter': 'veuillez vous connecter',
          'pour une experience optimisee , ':
              'pour une experience optimisee , ',
          "Bienvenue ,": "Bienvenue ,",
          'RECHERCHER (56242)': 'RECHERCHER (56242)',
          'France': 'France',
          'English': 'English',
          'Arabic': 'Arabe',
          'Choose Your Language': 'Choisissez votre langue',
          'Contact': 'Contact',
          'Mes favoris': 'Mes favoris',
          'Se connecter': 'Se connecter',
          'DEPOSER UNE ANNONCE': 'DEPOSER UNE ANNONCE',
          "This feature will be": "Cette fonctionnalité sera bientôt",
          "available": "disponible",
          "soon in the application": "dans l'application",
          "Sorry !  ": "Nous sommes désolés !  ",
          "Your Email": "Your Email",
          'Login': 'Login',
          "Don’t have an Account ": "Vous n'avez pas de compte",
          "Sign Up": 'Register',
          "Are you wante to modifier ?": "Are you wante to modifier ?",
          "Cancel": "Cancel",
          "yes": "yes",
          "this feature is not yet available in this version of the application ":
              "cette fonctionnalité n'est pas encore disponible dans cette version de l'application ",
          "Wooden": "Parquet",
          'Marble': "Marbre",
          "Tiled": "Carrelage",
          "Others": "Autre",
          "Delete": "Supprimer",
          "Update": "Éditer",
          'Search results are empty ': 'Search results are empty ',
          'Search results are empty ':"نتائج البحث فارغة",
          "Demande":"Demande",
        },
        'en_US': {
          "Filtrer":"Filter",
          'EFFACER':'TO ERASE',
          'Que rechercher vous ?':"What are you looking for?",
          "entre ville":"entre the city",
          "Type d\'annonce":"Type d\'annonce",
          "Demande":"Demande",
          'Search results are empty ': 'Les résultats de la recherche sont vides',
          "Entrez le nom de la ville ?":"Enter the name of the city ?",
          'Compte':'Compte',
          "Moins de 1 ans":"Less than 1 year",
          "1 à 5 ans":"1 to 5 years old",
          "5 à 10 ans":"5 to 10 years old",
          "10 à 20 ans": "10 to 20 years old",
          "20 à 30 ans":"20 to 30 years old",
          "30 à 50 ans":"30 to 50 years old",
          "50 à 70 ans":  "50 to 70 years old",
          "70 à 100 ans":"70 to 100 years old",
          "Plus de 100 ans":"Over 100 years old",
          "Area ": "Area",
          'Price': "Price",
          'Age': "Age",
          'Flooring': 'Flooring',
          "Bedroms": "Bedroms",
          "Kitchens": "Kitchens",
          "Bathrooms": "Bathrooms",
          'Main Abilites': 'Main Abilites',
          'Innir Abilites': 'Innir Abilites',
          'Addition Abilites': 'Addition Abilites',
          "following": "following",
          "Reservez ": "Reservez ",
          "update": "update",
          "Your ad is not adding": "Your ad is not adding",
          "Your ad is added": "Your ad is added",
          "success": "success",
          "Precedent": "Precedent",
          'Phone 1 :': 'Phone 1 :',
          'Phone 2 :': 'Phone 2 :',
          'Phone 3 :': 'Phone 3 :',
          " Entre L \' Phone": " Entre L \' Phone",
          " Entre L \' Description": " Entre L \' Description",
          'Description :': "Description :",
          " Entre L \' Titel": " Entre L \' Titel",
          "Title": "Title",
          "Update": "Update",
          "Delete": "Delete",
          "Wooden": "Wooden",
          'Marble': "Marble",
          "Tiled": "Tiled",
          "Others": "Others",
          "Select State": "property status",
          "Se Déconnecter": 'Log Out',
          "Tableau De Bord": 'Dashboard',
          'Informations': 'Information',
          'All': 'All',
          'apartment': 'Apartments',
          'rooms': 'Rooms',
          'house': 'House',
          'villa': 'Villa',
          'riad': 'Riad',
          'commercialSpace': 'Commercial',
          'office': 'Office',
          'land': 'Land',
          'farm': 'Farms',
          'Appartements': 'Apartments',
          'Chambre': 'Rooms',
          'Maison': 'House',
          "commercialeSpace": 'Commercial',
          "Bureau": 'Office',
          "Terre": 'Land',
          "Fermes": 'Farms',
          "Neuf": "New",
          "Bon état": "good",
          "A besoin de réparation": "needRepair",
          'Suivant': 'Next',
          'Property details': 'Property details',
          'Vente': 'Sale',
          'À location': 'For hire',
          'Catégorie': 'Category',
          'Adresse': 'Address',
          'Statut': 'Status',
          'Region': 'Region',
          'Ville': 'City',
          'Quartier': 'District',
          'select property': 'sselect property',
          'Location': 'Location',
          'Contact': 'Contact',
          'Mes favoris': 'My favorites',
          'Se connecter': 'Login',
          'DEPOSER UNE ANNONCE': 'PLACE AN ANNOUNCEMENT',
          'veuillez vous connecter': 'please login',
          'pour une experience optimisee , ': 'for an optimized experience , ',
          "Bienvenue ,": "Welcome ,",
          'RECHERCHER (56242)': 'SEARCH (56242)',
          'France': 'French',
          'English': 'English',
          'Arabic': 'Arabic',
          'Choose Your Language': 'Choose Your Language',
          'casablaca': 'casablaca',
          'Langues': 'Langues',
          'Contactez nous': 'Contactez nous',
          "Home": "Home",
          "This feature will be": "This feature will be ",
          "available": "available",
          "soon in the application": "soon in the application",
          "Sorry !  ": "Sorry !  ",
          "Your Email": "Your Email",
          'Login': 'Login',
          "Don’t have an Account ": "Don’t have an Account ",
          "Sign Up": "Sign Up",
          "Are you wante to modifier ?": "Are you wante to modifier ?",
          "Cancel": "Cancel",
          "yes": "yes",
          "this feature is not yet available in this version of the application ":
              "this feature is not yet available in this version of the application "
        }
      };
}
