import 'package:get/get.dart';

class Transation extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'ar_MA': {

          'Property details': 'تفاصيل اوضح',
          'Vente': 'بيع',
          'À location': 'للايجار',
          'Catégorie': 'فئة',
          'Adresse': 'عنوان',
          'Statut': 'الحالة',
          'Region': 'منطقة',
          'Ville': 'مدينة',
          'Quartier': 'حي',
          'select property': 'اختر خاصية',
          'Location': 'تأجير',
          'France': 'الفرنسية',
          'English': 'الانجليزية',
          'Arabic': 'العربية',
          'Suivant': 'التالي',
          'Langues': 'تغيير اللغة',
          'Contactez nous': 'اتصل بنا',
          'Choose Your Language': "اختر لغتك",
          'RECHERCHER (56242)': 'بحث (56242)',
          'Chat': 'دردشة',
          'Mes favoris': 'المفضلة لدي',
          'Se connecter': 'تسجيل دخول',
          'DEPOSER UNE ANNONCE': 'نشر اعلان',
          "Bienvenue ,": 'مرحبا ،',
          'pour une experience optimisee , ': 'لتجربة محسّنة ،',
          'veuillez vous connecter': 'الرجاء تسجيل الدخول',
          "Neuf": 'جديد',
          "Bon état": 'بحالة جيدة',
          "A besoin de réparation": 'يتطلب الصيانة',
          'Appartements': 'شقق',
          'Chambre': 'غرفة',
          'Maison': 'منزل',
          'Villa': 'فيلا',
          'Riad': 'رياض',
          'Commercial': "محل تجاري",
          'Bureau': 'مكتب',
          'Terre': 'أرض',
          'Fermes': 'مزارع',
          "All": 'الكل',
          "apartment": 'شقق',
          "rooms": 'غرفة',
          "house": 'منزل',
          "villa": 'فيلا',
          "riad": 'رياض',
          'commercialeSpace': 'محل تجاري',
          'office': 'مكتب',
          'land': 'أرض',
          'farm': 'مزارع',
          'Informations': 'معلومات',
          "Se Déconnecter": 'تسجيل الخروج',
          "Tableau De Bord": 'لوحة القيادة',
          "Select State": 'حالة الملكية',
          "Home":'الرئيسية',
          "This feature will be":"هذه الميزة سوف تكون",
          "available":"متاحة",
          "soon in the application":"  قريبا في التطبيق",
          "Sorry !  ":"نحن اسفون !!",
          "Your Email" : "الايميل",
          'Login':'تسجيل الدخول',
          "Don’t have an Account ":"لا أملك حسابا ",
          "Sign Up":'انشاء حساب',
          "Are you wante to modifier ?":"هل تريد تعديل هذا الاعلان ؟ ",
          "Cancel":"الغاء",
          "yes":"نعم",
           "this feature is not yet available in this version of the application ":"هذه الميزة غير متوفرة بعد في هذا الإصدار من التطبيق"
        },
        'fr_FR': {

          "Select State":  "Select State",
          "Se Déconnecter": 'Se Déconnecter',
          "Tableau De Bord": 'Tableau De Bord',
          'Informations': 'Informations',
          'All': 'Tout',
          'apartment': 'Appartements',
          'rooms': 'Chambre',
          'house': 'Maison',
          'villa': 'Villa',
          'riad': 'Riad',
          'commercialeSpace': 'Commercial',
          'office': 'Bureau',
          'land': 'Terre',
          'farm': 'Fermes',
          'Appartements': 'Appartements',
          'Chambre': 'Chambre',
          'Maison': 'Maison',
          'Villa': 'Villa',
          'Riad': 'Riad',
          'Commercial': 'Commercial',
          'Bureau': 'Bureau',
          'Terre': 'Terre',
          'Fermes': 'Fermes',
          "Neuf": "Neuf",
          "Bon état": "Bon état",
          "A besoin de réparation": "A besoin de réparation",
          'Suivant': 'Suivant',
          'Property details': 'Property details',
          'Vente': 'Vente',
          'À location': 'À location',
          'Catégorie': 'Catégorie',
          'Adresse': 'Adresse',
          'Statut': 'Statut',
          'Region': 'Region',
          'Ville': 'Ville',
          'Quartier': 'Quartier',
          'select property': 'select property',
          'Location': 'Location',
          'veuillez vous connecter': 'veuillez vous connecter',
          'pour une experience optimisee , ':
              'pour une experience optimisee , ',
          "Bienvenue ,": "Bienvenue ,",
          'RECHERCHER (56242)': 'RECHERCHER (56242)',
          'France': 'France',
          'English': 'English',
          'Arabic': 'Arabe',
          'Choose Your Language': 'Choisissez votre langue',
          'Chat': 'Chat',
          'Mes favoris': 'Mes favoris',
          'Se connecter': 'Se connecter',
          'DEPOSER UNE ANNONCE': 'DEPOSER UNE ANNONCE',
          "This feature will be":"Cette fonctionnalité sera bientôt",
          "available":"disponible",
          "soon in the application":"dans l'application",
          "Sorry !  ":"Nous sommes désolés !  ",
          "Your Email" : "Your Email",
          'Login':'Login',
          "Don’t have an Account ":"Vous n'avez pas de compte",
          "Sign Up":'Register',
          "Are you wante to modifier ?":"Are you wante to modifier ?",
          "Cancel":"Cancel",
          "yes":"yes",
          "this feature is not yet available in this version of the application ":"cette fonctionnalité n'est pas encore disponible dans cette version de l'application "


        },
        'en_US': {

          "Select State":  "property status",
          "Se Déconnecter": 'Log Out',
          "Tableau De Bord": 'Dashboard',
          'Informations': 'Information',
          'All': 'All',
          'apartment': 'Apartments',
          'rooms': 'Rooms',
          'house': 'House',
          'villa': 'Villa',
          'riad': 'Riad',
          'commercialSpace': 'Commercial',
          'office': 'Office',
          'land': 'Land',
          'farm': 'Farms',
          'Appartements': 'Apartments',
          'Chambre': 'Rooms',
          'Maison': 'House',
          "villa": 'Villa',
          "riad": 'Riad',
          "commercialeSpace": 'Commercial',
          "Bureau": 'Office',
          "Terre": 'Land',
          "Fermes": 'Farms',
          "Neuf": "New",
          "Bon état": "good",
          "A besoin de réparation": "needRepair",
          'Suivant': 'Next',
          'Property details': 'Property details',
          'Vente': 'Sale',
          'À location': 'For hire',
          'Catégorie': 'Category',
          'Adresse': 'Address',
          'Statut': 'Status',
          'Region': 'Region',
          'Ville': 'City',
          'Quartier': 'District',
          'select property': 'sselect property',
          'Location': 'Location',
          'Chat': 'Chat',
          'Mes favoris': 'My favorites',
          'Se connecter': 'Login',
          'DEPOSER UNE ANNONCE': 'PLACE AN ANNOUNCEMENT',
          'veuillez vous connecter': 'please login',
          'pour une experience optimisee , ': 'for an optimized experience , ',
          "Bienvenue ,": "Welcome ,",
          'RECHERCHER (56242)': 'SEARCH (56242)',
          'France': 'French',
          'English': 'English',
          'Arabic': 'Arabic',
          'Choose Your Language': 'Choose Your Language',
          'casablaca': 'casablaca',
          'Langues': 'Langues',
          'Contactez nous': 'Contactez nous',
          "Home":"Home",
          "This feature will be":"This feature will be ",
          "available":"available",
          "soon in the application":"soon in the application",
          "Sorry !  ":"Sorry !  ",
          "Your Email" : "Your Email",
          'Login':'Login',
          "Don’t have an Account ":"Don’t have an Account ",
          "Sign Up":"Sign Up",
"Are you wante to modifier ?":"Are you wante to modifier ?",
"Cancel":"Cancel",
"yes":"yes",
          "this feature is not yet available in this version of the application ":"this feature is not yet available in this version of the application "

}
      };
}
