import 'package:get/get.dart';

class Transation extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'ar_MA': {
          'Property details': 'تفاصيل اوضح',
          'Vente': 'بيع',
          'À location': 'للايجار',
          'Catégorie': 'فئة',
          'Adresse': 'عنوان',
          'Statut': 'الحالة',
          'Region': 'منطقة',
          'Ville': 'مدينة',
          'Quartier': 'حي',
          'select property': 'اختر خاصية',
          'Location': 'تأجير',
          'France': 'الفرنسية',
          'English': 'الانجليزية',
          'Arabic': 'العربية',
          'Suivant': 'التالي',
          'Langues': 'تغيير اللغة',
          'Contactez nous': 'اتصل بنا',
          'Choose Your Language': "اختر لغتك",
          'RECHERCHER (56242)': 'بحث (56242)',
          'Chat': 'دردشة',
          'Mes favoris': 'المفضلة لدي',
          'Se connecter': 'تسجيل دخول',
          'DEPOSER UNE ANNONCE': 'نشر اعلان',
          "Bienvenue ,": 'مرحبا ،',
          'pour une experience optimisee , ': 'لتجربة محسّنة ،',
          'veuillez vous connecter': 'الرجاء تسجيل الدخول',
        },
        'fr_FR': {
          'Suivant': 'Suivant',
          'Property details': 'Property details',
          'Vente': 'Vente',
          'À location': 'À location',
          'Catégorie': 'Catégorie',
          'Adresse': 'Adresse',
          'Statut': 'Statut',
          'Region': 'Region',
          'Ville': 'Ville',
          'Quartier': 'Quartier',
          'select property': 'select property',
          'Location': 'Location',
          'veuillez vous connecter': 'veuillez vous connecter',
          'pour une experience optimisee , ':
              'pour une experience optimisee , ',
          "Bienvenue ,": "Bienvenue ,",
          'RECHERCHER (56242)': 'RECHERCHER (56242)',
          'France': 'France',
          'English': 'English',
          'Arabic': 'Arabe',
          'Choose Your Language': 'Choisissez votre langue',
          'Chat': 'Chat',
          'Mes favoris': 'Mes favoris',
          'Se connecter': 'Se connecter',
          'DEPOSER UNE ANNONCE': 'DEPOSER UNE ANNONCE',
        },
        'en_US': {
          'Suivant': 'Next',
          'Property details': 'Property details',
          'Vente': 'Sale',
          'À location': 'For hire',
          'Catégorie': 'Category',
          'Adresse': 'Address',
          'Statut': 'Status',
          'Region': 'Region',
          'Ville': 'City',
          'Quartier': 'District',
          'select property': 'sselect property',
          'Location': 'Location',
          'Chat': 'Chat',
          'Mes favoris': 'My favorites',
          'Se connecter': 'Loging',
          'DEPOSER UNE ANNONCE': 'PLACE AN ANNOUNCEMENT',
          'veuillez vous connecter': 'please login',
          'pour une experience optimisee , ': 'for an optimized experience , ',
          "Bienvenue ,": "Welcome ,",
          'RECHERCHER (56242)': 'SEARCH (56242)',
          'France': 'French',
          'English': 'English',
          'Arabic': 'Arabic',
          'Choose Your Language': 'Choose Your Language',
          'casablaca': 'casablaca',
          'Langues': 'Langues',
          'Contactez nous': 'Contactez nous'
        }
      };
}
